/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter(clk, rst, en, q);
  wire _00_;
  wire _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  input clk;
  wire clk;
  input en;
  wire en;
  output [3:0] q;
  reg [3:0] q;
  input rst;
  wire rst;
  assign _02_[0] = ~q[0];
  assign _03_[1] = q[1] ^ q[0];
  assign _00_ = ~(q[1] & q[0]);
  assign _03_[2] = ~(_00_ ^ q[2]);
  assign _01_ = q[2] & ~(_00_);
  assign _03_[3] = _01_ ^ q[3];
  always @(posedge clk)
    if (rst) q[0] <= 1'h0;
    else if (en) q[0] <= _02_[0];
  always @(posedge clk)
    if (rst) q[1] <= 1'h0;
    else if (en) q[1] <= _03_[1];
  always @(posedge clk)
    if (rst) q[2] <= 1'h0;
    else if (en) q[2] <= _03_[2];
  always @(posedge clk)
    if (rst) q[3] <= 1'h0;
    else if (en) q[3] <= _03_[3];
  assign _02_[3:1] = q[3:1];
  assign _03_[0] = _02_[0];
endmodule
