/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_scan(clk, rst, en, scan_en, scan_in, scan_out, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input clk;
  wire clk;
  input en;
  wire en;
  wire [3:0] next_q;
  output [3:0] q;
  wire [3:0] q;
  input rst;
  wire rst;
  input scan_en;
  wire scan_en;
  input scan_in;
  wire scan_in;
  output scan_out;
  wire scan_out;
  assign _00_ = q[0] ^ q[1];
  assign next_q[1] = en ? _00_ : q[1];
  assign _01_ = ~(q[0] & q[1]);
  assign _02_ = ~(_01_ ^ q[2]);
  assign next_q[2] = en ? _02_ : q[2];
  assign _03_ = q[2] & ~(_01_);
  assign _04_ = _03_ ^ scan_out;
  assign next_q[3] = en ? _04_ : scan_out;
  assign next_q[0] = q[0] ^ en;
  scan_dff u_scan_ff0 (
    .clk(clk),
    .d(next_q[0]),
    .q(q[0]),
    .rst(rst),
    .scan_en(scan_en),
    .scan_in(scan_in)
  );
  scan_dff u_scan_ff1 (
    .clk(clk),
    .d(next_q[1]),
    .q(q[1]),
    .rst(rst),
    .scan_en(scan_en),
    .scan_in(q[0])
  );
  scan_dff u_scan_ff2 (
    .clk(clk),
    .d(next_q[2]),
    .q(q[2]),
    .rst(rst),
    .scan_en(scan_en),
    .scan_in(q[1])
  );
  scan_dff u_scan_ff3 (
    .clk(clk),
    .d(next_q[3]),
    .q(scan_out),
    .rst(rst),
    .scan_en(scan_en),
    .scan_in(q[2])
  );
  assign q[3] = scan_out;
endmodule

module scan_dff(clk, rst, scan_en, d, scan_in, q);
  wire _0_;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  reg q;
  input rst;
  wire rst;
  input scan_en;
  wire scan_en;
  input scan_in;
  wire scan_in;
  assign _0_ = scan_en ? scan_in : d;
  always @(posedge clk)
    if (rst) q <= 1'h0;
    else q <= _0_;
endmodule
